### ISSUE TITLE
createCors is not a function, difference between doc example and code

### ISSUE THREAD

**Issue by foufrix** [kwhitley/itty.dev#24]
Hi, after trying [this example ](https://itty.dev/itty-router/createCors#configuring-cors)

It gives me an error message stating, `createCors is not a function,` which suggests that no `createCors` function is exported. 

After looking at issue #21 I saw that `cors()` should be used.

Either update the doc or the code, don't know which variable you want to keep :D

Thank you for the package!

EDIT: 

After looking in depth saw that it's due to v4 to v5 migration

**Comment by kwhitley** [comment]
Thanks @foufrix!

Deleted old createCors.md page, which should remove it from polluting search... if you stumbled across it in a different way, please let me know!
