### ISSUE TITLE
Link to repos from docs

### ISSUE THREAD

**Issue by nathanclevenger** [kwhitley/itty.dev#4]
Unless I'm missing it somewhere, there doesn't seem to be any links to the repos for `itty-router`, `itty-durable`, etc from the docs.  I find myself regularly clicking on the "Edit this Page" link, then, clicking on `kwhitly`, then `Repositories` then trying to find the proper one.

I could make a pull request, but I'm not sure how/where you would want these links on each page.

**Comment by MajorTanya** [comment]
Not sure if you're still looking for this, but on [itty.dev](https://itty.dev), every project has both a NPM symbol and a GitHub symbol left-aligned in its title page, such as at https://itty.dev/itty-router.
![grafik](https://github.com/kwhitley/itty.dev/assets/39014446/89ca772e-5910-4de2-bb62-b14023e3ac8b)

In code, this seems to be managed somewhat dynamically here: https://github.com/kwhitley/itty.dev/blob/main/src/routes/%2Blayout.svelte#L52-L67

**Comment by nathanclevenger** [comment]
Thanks @MajorTanya - yes, it got resolved shortly after I created the ticket, but this never got closed.  Thanks
